platform :ios, '8.0'
use_frameworks!

pod 'RealmSwift'
pod 'Alamofire', '~> 1.2'
pod 'pop', '~> 1.0'
pod 'PureLayout'
pod 'Mantle'
pod 'AFNetworking'
pod 'GraphKit'
pod 'MWFeedParser/NSString+HTML'
pod 'Firebase'
pod 'TTTAttributedLabel'
pod 'ECSlidingViewController', '~> 2.0.3'
pod 'Cartography'
