# -*- coding: utf-8 -*-
import json
from random import randint
from collections import Counter
import re
from itertools import takewhile

json_data = open('/Users/regan/Desktop/export.json').read()

def firebase_sanitize(string):
    unicodeString = string.decode('utf-8')
    for i, forbidden in enumerate(['.', '#', '$', '/', '[', ']', '\n', '\r', u'’',]):
    	f = unicode(forbidden)
        unicodeString = unicodeString.replace(f, u'&' + unicode(i) + u'&')
    return unicodeString

def parseShortFieldNumberAndTitle(rawTitle):
	comps = course['title'].split(' - ')
	if len(comps) > 1:
		raw_number = comps[0]
		if raw_number[0].isupper() and raw_number[1].isupper() or 'E-PSCI' in raw_number:
			num_comps = raw_number.split(' ')
			shortField = num_comps[0]
			number = num_comps[1]
			title = ' - '.join(comps[1:])
			if len(num_comps) != 2:
				print "Oddball", shortField, number, raw_number, course['title']		
			return firebase_sanitize(shortField), firebase_sanitize(number), firebase_sanitize(title)
	number = ''
	title = ' - '.join(comps)
	return '', firebase_sanitize(number), firebase_sanitize(title)

commas = []
ands = []
oneName = []
oddballs = []

def parseName(raw_name):
	comps = [x for x in raw_name.split(' ') if x != ' ' and x != '']
	lenComps = len(comps)
	if lenComps == 2:
		return comps[0], '', comps[1]
	elif lenComps == 3:
		return comps[0], comps[1], comps[2]
	else:
		if raw_name == 'Roland Gerhard Fryer Jr.':
			return 'Roland', 'Gerhard', 'Fryer'
		elif raw_name == 'members of the Department':
			return None
		elif raw_name == 'Leonard W. J. van der Kuijp':
			return 'Leonard', 'W. J.', 'van der Kuijp'
		elif raw_name in ['Maria Celeste Moreno Palmero', 'Maria celeste Moreno palmero ']:
			return 'Maria', 'Celeste Moreno', 'Palmero'
		elif raw_name == 'Alejandro de la Fuente':
			return 'Alejando', 'de la', 'Fuente'
		elif raw_name == 'S. C. Samuel Kou':
			return 'S.', 'C. Samuel', 'Kou'
		elif raw_name == 'William Mills Todd III':
			return 'William', 'Mills', 'Todd'
		elif raw_name == 'Everton Vargas da Costa':
			return 'Everton', 'Vargas', 'da Costa'
		elif raw_name == 'Alison Frank Johnson 5313':
			return 'Alison', 'Frank', 'Johnson'
		elif raw_name == 'Luis Jaime Castillo Butters':
			return 'Luis', 'Jaime Butters', 'Castillo'
		else:
			print "Invalid len(name) of " + str(lenComps), raw_name

def sanitizedName(raw_name):
	names = parseName(raw_name)
	if names is None:
		return None
	first, middle, last = names
	return firebase_sanitize(first), firebase_sanitize(middle), firebase_sanitize(last)

def parseFaculty(course):
	if 'faculty' in course:
		raw_faculty = course['faculty']
		# Remove the '(East Asian Studies)' in: Albert Einstein (East Asian Studies)
		raw_faculty = re.sub(r'\(.*?\)', '', raw_faculty)
		comps = raw_faculty.split(' ')
		if ' and ' in raw_faculty:
			andSplit = raw_faculty.split(' and ')
			if len(andSplit) != 2:
				print "Invalid andSplit " + str(andSplit)
			else:
				commaSplit = andSplit[0].split(', ')
				return map(sanitizedName, commaSplit + [andSplit[1]])
		elif ',' in raw_faculty:
			commaSplit = raw_faculty.split(', ')
			return map(sanitizedName, commaSplit)
		else:
			return [sanitizedName(raw_faculty)]
	return None

def parseDepartment(course):
	if 'department' in course:
		return course['department']

def parseTerm(course):
	raw_term = course['term']
	if raw_term in ['Spring 2015-2016', 'Spring 2016', 'Spring (full-semester) 2016']:
		year = '2016'
		term = 'Spring'
	elif raw_term in ['Fall 2015-2016', 'Fall 2015', 'Fall (full-semester) 2015']:
		year = '2015'
		term = 'Fall'
	elif raw_term in ['Summer 2015']:
		year = '2015'
		term = 'Summer'
	elif raw_term == 'Full Year 2015':
		year = '2015'
		term = 'Full Year'
	else:
		print "Invalid term", title, course['term']
	return term, year

def digit(string):
	return string.isdigit()

meetings = Counter()

def parseTimeString(timeString):
	comps = timeString.split(' ')
	timeComps = comps[0].split(':')
	hours, minutes = int(timeComps[0]), int(timeComps[1])
	if minutes == 59:
		minutes = 0
		hours += 1
	elif minutes == 29:
		minutes = 30
	if comps[1] == 'p.m.' and hours < 12:
		hours += 12
	return str(hours) + ':' + str(minutes)

def parseMeetingString(raw_meeting, debug=False):
	j = 0
	for i, char in enumerate(raw_meeting):
		if char.isdigit():
			j = i
			break
	day_string = raw_meeting[0:j]
	time_string = raw_meeting[j:]
	split_time = time_string.split(' - ')
	begin_time = parseTimeString(split_time[0])
	end_time = parseTimeString(split_time[1])

	dayDict = {0: "Sun", 1: "Mon", 2: "Tues", 3: "Wed", 4: "Thur", 5: "Fri", 6: "Sat"}
	dayStrings = ['Monday', 'Mon', 'M', 'Tuesday', 'Tu', 'Wednesday', 'Wed', 'W', 'Thursday', 'Thu', 'Th', 'Friday', 'F']
	dayNums = [1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5]
	days = set()
	for string, num in zip(dayStrings, dayNums):
		if string in day_string:
			days.add(num)
			day_string = day_string.replace(string, '')
	return [{'day': day, 'beginTime': begin_time, 'endTime': end_time} for day in days]

def parseMeeting(course, term, year, location, latitude, longitude, faculty):
	raw_meeting = course['meeting'].replace(u'\xa0', '')
	if raw_meeting == 'tbd':
		return [{'term': term, 'year': year, 'meetings': [], 'location': location, 'latitude': latitude, 'longitude': longitude, 'faculty': faculty}]
	else:
		parts = raw_meeting.split(';')
		meetings = []
		for part in parts:
			meetings.append(parseMeetingString(part))
		return [{'term': term, 'year': year, 'meetings': meetings, 'location': location, 'latitude': latitude, 'longitude': longitude, 'faculty': faculty}]

def parseLocation(course):
	if 'location' in course:
		return course['location']

def parseLevel(course):
	if 'level' in course:
		return course['level']

def parseCredits(course):
	if 'credits' in course:
		credits = course['credits']
		if credits is None:
			return credits
		credits = credits.replace('\n', '')
		credits = credits.replace('\t', '')
		credits = credits.replace(u'\xa0', '')
		return credits

locPattern = re.compile('location:\".+?\"')
namePattern = re.compile('name:\".+?\"')

def parseMapLocation(course):
	if 'mapLocation' in course and course['mapLocation'] is not None:
		locResult = locPattern.search(course['mapLocation'])
		locString = locResult.group(0).replace('location:"', '')
		location = locString.replace('"', '').split(',')
		lat = location[0]
		longitude = location[1]
		nameResult = namePattern.search(course['mapLocation'])
		nameString = nameResult.group(0).replace('name:"', '')
		name = nameString.replace('"', '')
		return name, lat, longitude
	else:
		return '', '', ''

def mergeCourseDicts(a, b):
	ameet = a['meetings'] if a['meetings'] is not None else []
	bmeet = b['meetings'] if b['meetings'] is not None else []
	a['meetings'] = a['meetings'] + b['meetings']
	return a

allCourses = {}
titles = Counter()
for course in json.loads(json_data):
	courseDict = {}
	if course['school'] != 'Faculty of Arts and Sciences':
		continue
	shortField, number, title = parseShortFieldNumberAndTitle(course['title'])
	courseDict['catalogNumber'] = course['number']
	courseDict['school'] = course['school']
	courseDict['department'] = parseDepartment(course)
	term, year = parseTerm(course)
	location = parseLocation(course)
	locName, latitude, longitude = parseMapLocation(course)
	faculty = parseFaculty(course)
	courseDict['meetings'] = parseMeeting(course, term, year, location, latitude, longitude, faculty)
	courseDict['level'] = parseLevel(course)
	courseDict['credits'] = parseCredits(course)
	courseDict['description'] = course['description']
	courseDict['notes'] = course['notes']
	courseDict['prereqs'] = course['prereqs']
	courseDict['examGroup'] = course['examGroup']

	displayTitle = shortField + ' ' + number + ' ' + title
	if displayTitle == 'EXPOS 20 Expository Writing 20':
		# print faculty
		if faculty[0][2] == 'Mitchell':
			if year == 2015:
				title = 'American Criminals'
				description = 'The United States is a country fascinated with crime stories. But why do crime novels attract us? What do they reveal about where we come from, what we believe in, and who we are? This course will explore these and other related questions by studying fictional and nonfictional accounts of crimes committed in the United States by its citizens. In our first unit, we’ll consider how our notions about who criminals are change over time by examining the historical case of Lizzie Borden. The case, narrated by early crime writer Edmund Pearson, represents an infamous instance of miscarriage of justice in American history. In the following unit, we’ll explore how our ideas about criminality can change even within a single narrative. We’ll do so by looking at how two different media —fiction and film— portray the same crime story. Using both Dashiell Hammett’s novel The Maltese Falcon and the film version directed by John Huston and starring Humphrey Bogart, we’ll discuss how criminal identities shift in surprising ways in this story set in early twentieth century San Francisco. Finally, in our third unit, students will research a crime that occurred in their hometown, and think about how that crime might have been shaped by the town’s specific culture. Here students will draw on theoretical discussions about culture and criminality and uncover materials from the public record.' 
			else:
				title = 'The Femme Fatale'
				description = 'An intensive seminar that aims to improve each student’s ability to discover and reason about evidence through the medium of essays. Each section focuses on a particular theme or topic, described on the Expos Website. All sections give students practice in formulating questions, analyzing both primary and secondary sources and properly acknowledging them, supporting arguments with strong and detailed evidence, and shaping clear, lively essays. All sections emphasize revision.'
		elif faculty[0][2] == 'Achterberg':
			title = 'Paradox in Public Health'
			description = 'What happens when public health efforts to improve the wellbeing of a population undermine the wellbeing of individuals in that population? Can this outcome be avoided? Public health is characterized by the implications of this fundamental paradox: the health needs of a population are often at odds with the health needs of the very individuals who comprise that population. How does this larger paradox play out across various public health campaigns? In this class, we will use scientific articles to consider potential paradoxes in public health, both historical and contemporary. In Unit 1, we will wrestle with issues of current vaccination requirements, and consider the intersection of personal choice versus societal responsibility using current MMR (measles, mumps and rubella) vaccines. In Unit 2, students will debate the nature of public health motivation and practice—who decides what existing public health needs are? Two case studies will guide this discussion: goiter—a successfully eliminated (but now reemerging!) disease of micronutrient deficiency—and ongoing tobacco-control efforts. In Unit 3, students will conduct their own research on a controversial modern public health issue of their choice, and consider how the larger tension between the individual and the population is manifested in the student’s particular selected public health controversy.'	
		elif faculty[0][2] == 'Barber':
			title = 'Wizards and Wild Things'
			description = 'Once upon a time, there was no Harry Potter. Once upon a time, there was no such thing as children’s literature. When and if children learned to read, they read what grown-ups read. How then did writing for children as we now know it come of age? Why does the genre have such an enduring hold on our cultural imagination, even as it continues to provoke sharp debate over its greater purpose and value? Are classic children’s books like The Wizard of Oz, The Wind in the Willows, and The Cat in the Hat instructive or subversive, didactic or liberating? In this course we’ll examine selections from three centuries of popular prose and verse written expressly for and about children as we investigate how this eclectic canon reflects evolving ideas about childhood, changing views about educating and enchanting young readers, and persistent disputes over what and how children should learn from books. In Unit 1 we’ll survey landmark works in English for children from the Puritan through the Victorian eras, including the New England Primer, Grimms’ Tales, and Alice in Wonderland, as we consider what these texts tell us about the origin and evolution of the genre. In Unit 2 we’ll examine works by touchstone authors for younger readers including Mark Twain, Louisa May Alcott, Rudyard Kipling, E. B. White, C. S. Lewis, Maurice Sendak, and others, drawing on the critical perspectives of thinkers such as John Locke, Bruno Bettelheim, Alison Lurie, and Marina Warner to assess arguments about the essential function of imaginative literature from infancy through adolescence. In the final unit, students will conduct their own research to place a major children’s author of their choice in a relevant cultural and historical context.'
		elif faculty[0][2] == 'Roth':
			title = 'The Narrative Self'
			description = '“Life must be understood backwards, but lived forwards” the philosopher Kierkegaard wrote. Sartre, in one of his novels, develops the thought: “You have to choose: live or tell.” Both suggest that living one\'s life and telling the story of it are mutually exclusive. Over the past few decades, many philosophers have disagreed, developing the view that understanding one\'s life as a story is not only something that most of us do, but allows us to become full persons and to live well. We will begin the course by considering some of these recent views. Are we right to speak of chapters of our lives and authoring our selves? To explain someone\'s behavior by referring to her character, or alternatively her role? To use literary genres such as tragedy to describe events in real life? What is entailed by such metaphors? Do they withstand careful scrutiny? Do our lives enact typical narrative arcs? Should they? Or do such claims confuse fiction and reality? In the middle part of the course, we will look at two fictional works that investigate similar issues. In Julian Barnes\'s The Sense of an Ending, the narrator\'s understanding of his life is upset by revelations concerning his past; the novel explores the fallibility of memory and its relation to material evidence. In the recent Swedish film Force Majeure, a wealthy family\'s ski vacation is upset when the husband reacts to an avalanche in an apparently cowardly manner, raising questions about character and situation, and what it means to be brave. At the end of the course, we will consider some critics of narrative self-understanding, as well as more specific applications of it. Do empirical studies challenge the idea that we have stable character? Does understanding one\'s life as a story preclude living in the moment? If lives are like stories, do they have a genre? Students could begin from these or other questions as they develop their own final research topics.'
		elif faculty[0][2] == 'Wilkinson':
			title = 'The End of the World As We Know It?'
			description = 'Think of Harvard in ruins, its halls picked clean by marauders (like those in Mad Max) or by hungry undead (think World War Z). But what would it really be like to experience society’s collapse? In some artistic visions, Apocalypse offers not just devastation, but a clean slate – room to start over. How bad would the “end of civilization” really be? Ten years ago, Jared Diamond’s book Collapse described ancient and modern “ecocides” – social collapses after unsustainable environmental abuse. Diamond warned that “within the lifetimes of the children and young adults alive today,” our environmental problems, if not corrected, would similarly provoke “warfare … disease epidemics, and collapses of societies.” But many historians and archaeologists have vigorously challenged Diamond’s account of the past, fueling an ongoing debate about collapse. What collapse is, what causes it, and whether its consequences might be catastrophic or quite livable for some remain contentious.  Whether in our best research or in the latest film, collapse is hard to pin down. Together, we’ll chase collapse through the ruins. We’ll read short fiction by George R. R. Martin and Elizabeth Bear, asking how post-apocalyptic visions balance annihilation and resilience. We’ll then compare prominent scholarly models for actual social collapse. How do such models illuminate the past – and the present? Finally, we’ll study the evidence for alleged social collapses around the world, from the Late Bronze Age Aegean to the barren slopes of Rapa Nui/Easter Island. The journey may be sobering – but perhaps the “end of civilization” isn’t the end of the world, after all.'
		elif faculty[0][2] == 'Rennix':
			title = 'Breaking the Rules'
			description = 'Everyone lives by rules, no matter how free they may feel. Some of these rules are written; others are unspoken. While we typically associate political rights with what it means to be “free,” the seemingly small social conventions of everyday life can limit our real or perceived liberties in powerful ways, too. The codes of conduct we follow when, for example, we use social media, when we go on dates, or when we work for a company all have the capacity to rein us in, and if we knowingly or unknowingly violate those norms, our freedom may be at the price of our membership in a community. This course will use literature and film to interrogate the relationship between social rules and individual freedom while considering the following questions: What does it really mean to be “free”? How does social obligation impact our access to personal freedom? Are we even aware of the ways that society controls our behavior, or are rules of social conduct largely invisible? As we seek the answers to these questions, we’ll start Unit 1 by performing close analysis of several short stories from both American and international authors—including Willa Cather, Flannery O’Connor and National Book Award winner Ha Jin—and discuss how they negotiate the relationship between individual desire and social expectation. In Unit 2, we’ll turn to films like Mean Girls, The Social Network, and The Graduate as we read theories of individual and collective freedom, questioning how the socially constrained environments of high school and college impact individuals’ behavior and choices. Finally, we will conclude with a culminating research paper in which students will choose from novels, movies, or television series like Mad Men and Downton Abbey, in order to deconstruct the social pressures that impinge on us today.'
		elif faculty[0][2] == 'Richardson':
			title = 'God and Government'
			description = 'The separation of church and state is often considered to be a cornerstone of modern democracy, but this idea has nevertheless been a difficult concept to put into practice. Must the state completely avoid any entanglement with religious groups, or merely act in a non-preferential manner toward them? How does a state determine whether a given belief or practice is religious (and thus deserving of legal protection) or simply ethical or cultural in nature? Is the ideal of a neutral political secularism even possible or desirable? And what should we think of the many global actors, from Latin America to the Middle East to Sub-Saharan Africa, who reject this ideal entirely? This course will consider the many questions and challenges raised by religious diversity for the modern state. We begin in the first unit by considering two influential early accounts of the proper relationship of governments to religiously diverse populations, James Madison’s “Memorial and Remonstrance” and Jean-Jacques Rousseau’s “On Civil Religion.” In the second unit, we will consider several judicial decisions from the U.S. Supreme Court and the European Court of Human Rights, which highlight the contentious legal landscape over the concept of “religious freedom.” Our final unit turns to the international stage to examine several case studies from Brazil, Palestine, Nigeria, and India, to see how religious diversity is shaping contemporary global conflict.'
		elif faculty[0][2] == 'Becker' and faculty[0][0] == 'Christina':
			title = 'Woolf and Hemingway'
			description = 'Ernest Hemingway and Virginia Woolf—few authors of the twentieth century have been as celebrated and as influential as these two great literary stylists. Yet it’s also hard to imagine two authors more unlike. For many readers, Hemingway epitomizes the writer-as-sportsman or adventurer, and his stripped-down writing seems to advocate a masculine ethic of tight-lipped toughness and restraint. By contrast, Woolf is often regarded today as the century’s great female writer and forerunner of contemporary feminism; her writing—ethereal, abstract, impressionistic—seems to embody a distinctively female aesthetic. In this course, we will read Woolf and Hemingway together, side by side; and in the essays we write, we will investigate what really distinguishes them—in terms of gender and art (among other things)—and consider how modernist literature may be configured between the opposing values these two icons have come to represent. Primary texts will include short stories by Hemingway, critical essays and short fiction by Woolf, Hemingway’s novel A Farewell to Arms, and Woolf’s novel Mrs. Dalloway.'
		elif faculty[0][2] == 'Becker' and faculty[0][0] == 'Peter':
			title = 'Slave Narratives'
			description = 'Written from the late eighteenth to the late nineteenth century in the United States, slave narratives represented the story from slavery to freedom, the escape from the South to the North, and the intellectual journey towards literacy and public speaking. This course examines some famous representatives of the genre and the complex questions it provoked as well as post-Civil Rights modifications of such narratives. In the first weeks, we will investigate the popular Narrative of the Life of Frederick Douglass (1845) as well as the sensational and widely read account of William and Ellen Craft’s flight to Boston, Running a Thousand Miles for Freedom (1860). We will analyze what roles literacy and rhetoric played in these texts, and hone in on the relationship between the black American writers of slave narratives and their white editors, who oversaw what was published, edited the narratives, vouched for their truth-value, and appended them with documents. In our second unit, we will focus on Toni Morrison’s Beloved (1987) to look at how modern writers modified and updated the genre after the 1960s. How did African American authors rewrite the slave narratives and their conventions? How do their portrayals of the slave community and the language of slavery differ from their predecessors? Finally, we will examine how the genre of the slave narrative changes in the hands of a white director. How does Quentin Tarantino’s Django Unchained (2012), Oscar-nominated yet also denounced as incendiary, modify the genre and the interaction between white editors and black American slaves? Our primary readings will be accompanied by seminal essays on the slave narratives, their literary development, and their high current cultural stakes.'
		elif faculty[0][2] == 'Betz':
			title = 'To Have Faith in America'
			description = 'The United States is arguably the most religiously diverse nation in the world. Americans possess a dizzying array of religious beliefs and behavior, and the First Amendment declares all are free to practice their faith. How do Americans—even the nonreligious—experience this religious panoply? Moving beyond abstract theology, this course explores the broad concept of lived religion. Across the United States, levels of religiosity remain high and recent controversies over a proposed Islamic community center in Lower Manhattan, Supreme Court rulings on female employees’ access to contraception, and this summer’s religious resistance to same-sex marriage all testify to the persistence of devout religious belief. How might we balance the tension between an essentially secular national constitution and a Bill of Rights that guarantees the free exercise of religion? Are there common religious tenets that all Americans must share? Or should the public square be kept “naked” of religious adornment so as to welcome all? Through readings in fiction, law, history and sociology, we’ll tackle these fundamental questions. In Unit One, we’ll read Disgraced, Ayad Akhtar’s 2013 Pulitzer Prize-winning play, in order to explore how religion affects intimate relationships among friends and co-workers. In the following unit, we’ll dissect two leading legal scholars’ arguments over the place of religion in the public sphere, such as the inclusion of intelligent design in biology curricula and the placing of a crèche and menorah in front of city halls. In the final unit, we’ll explore the limits of religious freedom through a series of short case studies involving snake handling, home schooling, and kirpan wearing. In this final unit, students will write a research paper on a religious freedom topic of their choosing.'
		elif faculty[0][2] == 'Tierney':
			title == 'The Science of Emotion'
			description == 'Reason has been routinely championed as the epitome of human achievement and framed as profoundly at odds with emotion. For much of the 20th century, scientists had even characterized emotion as unimportant. However, after the past 30 years of research, we now understand emotion to be a crucial factor in human behavior, including reasoning. This class will focus on the science of emotion. In Unit 1, we’ll explore what emotion is as we read several scientists’ divergent theories, including Joseph LeDoux and Antonio Damasio, who disagree on whether love is an emotion. To help us evaluate their conclusions, we will consider a crucial theory offered by Paul Ekman, whose research on facial expressions of emotion was largely responsible for the modern field of emotion science. In Unit 2, we’ll explore the conundrum that emotions are at the heart of individual—and thus seemingly subjective—experience and yet have so many elements that seem to be universal among humans of all cultures. We’ll read sources that outline the “laws of emotion” that differentiate between emotion and feelings, and that present interesting data on emotion in children living in poverty. Our final unit will take up the matter of how cognition and emotion interact and give students an opportunity to research one of many perplexing questions in this subfield of emotion science: What, for example, is the role of emotion in decision-making? How does emotion interact with learning or moral judgments? How does emotion operate in adolescence or in various pathologies?'
		elif faculty[0][2] == 'Unrue':
			title = 'The Voice of Authority'
			description = 'In our daily lives we negotiate our relation to the authority of government, religion, school, parents, and peers. But what is authority? How does an entity gain authority in the first place? What happens when authority is abused? What does it mean to challenge authority? And what does authority have to do with human rights? We’ll begin by reading the many-times-banned One Flew Over the Cuckoo’s Nest, and we’ll investigate that explosive novel’s complex and nuanced treatment of, and reaction to, authority. Next, we’ll read work by one or more international authors. These formerly or currently “at-risk” writers will visit our class, and we will analyze their work and what it reveals about authority and what happens when a writer who challenges governmental and cultural authority speaks openly about, and through, her/his work. This ongoing inquiry into the nature of authority will shape our research topics in the third unit, when we will investigate and theorize answers to questions arising out of our explorations of such topics as authority and: education, language and rhetorical strategy, politics, human rights, and art.'
		elif faculty[0][2] == 'Wilson':
			title = 'Why Shakespeare?'
			description = 'Shakespeare, we have all been told, is extremely important. You might agree or disagree with this pronouncement, but do you know why Shakespeare matters to so many people? Why does every high school in America assign Shakespeare? Why did the world erupt with jubilation on his 450th birthday in April 2014? Does Shakespeare deserve all this fuss, or is he really overrated? In this section, Shakespeare lovers and haters alike are invited to consider the question of Shakespeare’s popularity by looking into the relationship between his method of artistic creation and the values of the modern world. We’ll begin with a reading of the most famous artwork of the past millennium, Hamlet, a play about a bad philosopher trying to avenge his father’s murder. We’ll proceed with a study of Macbeth, where a celebrated war hero goes mad murdering his way into political power. Here we’ll start to see the ways Shakespeare and modern thought speak to each other (and don’t) by looking at two recent productions of Macbeth influenced by the twentieth-century invention of psychology – Alan Cummings’s 2013 one-man show on Broadway in which “it’s all in his head,” and Michael Fassbender’s 2015 film in which the hero returns from war with post-traumatic stress disorder (PTSD). We’ll also run Macbeth through some theories of criminology, a field that claims to offer scientific explanations for why crime happens. Finally, we’ll take a step back and ask, “Why Shakespeare?” and entertain answers ranging from the cynical (Shakespeare is a dead, white male that other dead, white males have used to promote the values of dead, white males) to the euphoric (Shakespeare is universal; Shakespeare invented the human).'
		elif faculty[0][2] == 'Ziparo':
			title = 'Dangerous Speech'
			description = 'On the playground, the teacher tells the teased child that “sticks and stones can break your bones, but names can never hurt you.” But we know that speech can hurt; a cross burning on your lawn can damage you far more profoundly than a slap across the face. In this course, we’ll examine the extent to which the First Amendment protects “dangerous speech”– a category that includes calls to violent action, racist abuse, and the communication of “subversive” political ideas. Our first unit will focus on a close reading of a recent Supreme Court case: Brown v. Entertainment Merchants Association, a decision striking down California’s ban on the sale of violent video games to minors. We’ll ask: how do Supreme Court Justices argue about dangerous speech? Next, we’ll broaden our scope to speech that incites violence. We’ll look to decisions applying free speech principles to communist agitators, cross burners, and racist protestors, and examine the theory behind the First Amendment. When does speech go too far? Our third unit will focus on hate speech – speech that vilifies a group based on, for example, its race, ethnicity, religion or sexual orientation. America is exceptional in its protection of hate speech; no other country affords so much protection for, in Justice Holmes’s words, the “thought that we hate.” Students will have the opportunity to choose a hate speech case or topic, either in the United States or abroad, to research in depth, using primary sources to ground the case in its contemporary context.'
		elif faculty[0][2] == 'Doherty':
			title = 'War Stories'
			description = 'How should we represent the horrors of war, and how should we remember it? These are questions that have fascinated writers since the time of Homer, but the answers to these questions changed in the modern era, when war started to seem less noble and heroic and more totalizing and destructive. This course looks at artistic representations of modern warfare and asks what effects war has on those who survive it. What happens when the body is whole, but the mind is broken? How does war live on the memories of those who fought, or in the collective memory of a nation? Can—or should—art be made out of these painful, violent experiences? We’ll start off with Tim O’Brien’s The Things they Carried, a powerful collection of stories based on O’Brien’s experiences as a solider in Vietnam. The stories encourage us to ask how truthfully we remember and what moral judgments we make when we choose which stories to tell. From there, we’ll pursue questions about memory and morality further by studying literature about the Great War, including Ernest Hemingway’s A Farewell to Arms. We’ll ask how national politics form in and around these wars and their legacies. Our last unit brings all of these topics together as we move from literature to the movies. We’ll watch Francis Ford Coppola’s Apocalypse Now, a movie that quickly became a classic of New Hollywood, and Zero Dark Thirty, Kathryn Bigelow’s recent depiction of the War on Terror. Throughout the course, we’ll debate whether the experience of war can ever be adequately communicated to those who weren’t there, and whether these attempts can prevent future generations from repeating the mistakes of the past.'
		elif faculty[0][2] == 'Fobi': 
			title = 'Sports and the Law'
			descripton = ' The world of sports is one of the most dynamic and complete microcosms of American life. Since the advent of big-money professional and “amateur” athletics at the dawn of the 20th century, sports has had to confront a range of important issues: race, gender, labor versus ownership, drugs, money, violence, and economic freedom. Sports has also, at its best, represented an egalitarian ideal: the only barrier to excellence is one\'s own talent and commitment. At moments when sports has advanced this ideal (Jackie Robinson, Title IX) it can push society forward. When, however, people or communities lose perspective on the place and meaning of sports, the results can be disastrous or even tragic (Jerry Sandusky, performance enhancing drug scandals). We will address these issues through a series of extracts from court cases, articles, and documentary films that will provide us with a nuanced view of sports. Using these sources, students will craft essays that present powerful arguments about the role and place of sports within American life.'
		elif faculty[0][2] == 'Fu':
			title = 'Who Owns the Past?'
			description = ' Our culture’s most iconic archaeologist is the glamorous Indiana Jones—a steely-eyed swashbuckler who cracks his leather bullwhip and fearlessly (with the exception of snakes) raids tombs for priceless relics. But who really are archaeologists and what do they actually do as discoverers and curators of the past? In our first unit, we will consider the rights and problems revolving around the passage of NAGPRA (The Native American Graves Protection and Repatriation Act) and in particular its relation to Harvard’s famous Peabody Museum. How is this significant piece of legislation, which argues for the return of objects to tribes in the United States, viewed by those Native American tribes, museums, and archaeologists themselves? In our second unit, we grapple with the very mission of archaeology. How do archaeologists think about the process of collecting data--often apparently scant, fragile, and historically distant--and then its interpretation? How much can archaeologists claim to know about the human past? To help us frame this question we will replicate an experiment done by archaeologists in studying designs on tombstones in Harvard’s own backyard. In our final unit, students will probe the ways in which political regimes use archaeology to legitimate a version of the past they favor. We will touch upon contradictory and competing narratives of the past between Israel and Palestine, Nazi Germany\'s use of archaeology to justify the values of the Third Reich, and Saddam Hussein\'s appeals to history to glorify his reign.'	
		elif faculty[0][2] == 'Mukherjee':
			title = 'Colonialism and Resistance'
			description = ' In Shakespeare’s seemingly fairy-tale-like play, The Tempest, a god-like European magician tames an ugly monster on an island far removed from Europe. In Heat and Dust, a cross-cultural novel written centuries later by European author, Ruth Prawer Jhabvala, heroic British rulers save powerless widows in India from the monstrosity of being forced to burn themselves on their husbands’ funeral pyres. Yet European power over non-Eurocentric cultures does not go unchallenged: so, we find Shakespeare’s monster begin to plot revenge against the powerful European magician. And even more strikingly, in the hugely popular contemporary British movie, Bend It Like Beckham, a non-western teenaged girl—instead of being saved by English heroes—now starts dreaming of bending the soccer ball herself like the heroic David Beckham! In this course, we’ll explore some of the myriad ways in which creative voices from different times capture the phenomenon of colonialism, the process by which European nations systematically gained power over much of the non-European world, producing effects that reverberate globally to this day. At the same time, we’ll analyze how such narratives depict the equally significant ways in which non-European peoples resisted colonial power and continue to resist its ongoing legacy. We’ll begin by reading The Tempest, a fascinating tale of magicians and monsters, princesses and sprites, shipwrecks and islands that raises profound questions about the forcible manner in which Europeans established colonies in the New World, as well as the violent ways in which natives resisted them. Does this English play represent the forceful strategies of the Europeans and the violence of the natives in a manner that justifies the early colonial project as necessary for improving “lesser” peoples or that critiques it as unjustified in ousting locals? Our second course unit transitions to modern colonialism, the more full-fledged political, economic, and cultural domination of non-European nations. With the help of leading postcolonial theorist Edward Said, we’ll examine Heat and Dust as a window to understanding a complex form that colonial power and acts of resistance to it can take: what happens, in other words, when those in power and those opposing it don’t use sheer force but rather ideas and language as their tools for empowerment? We’ll conclude the course by comparatively considering the movie, Bend It Like Beckham, alongside three short stories by Albert Camus, Salman Rushdie, and Sherman Alexie, respectively, to evaluate avenues as varied as sports, religion, standardized tests, and even recreational drugs through which today’s post-colonial populations across the globe engage in dismantling the colonial legacy. As we do so, we’ll also ask what kinds of role, if any, formerly colonizing European powers should play in such endeavors.'
		elif faculty[0][2] == 'Stalford':
			title = u'The Knife’s Edge'
			description = ' For most of human history, surgery has been a brutal, terrifying affair. Operations were carried out as quickly as possible to the sound of blood-curdling screams, and often ended in the patient’s death. Historian of medicine Martin Pernick observed of surgeons before the advent of anesthesia that “the emotional ability to inflict vast suffering was perhaps the most basic of all professional prerequisites.” To say the state of the art has advanced since then is an understatement—incredibly, it is now even possible for complex surgeries to be carried out by robot, directed remotely by surgeons hundreds of miles away. Yet whether the scalpel is wielded by robotic arms or flesh-and-blood hands, it remains the case that operations are performed by human beings who are fallible, on bodies that are mortal, and there is still no way to wholly eliminate risk. As the surgeon and writer Atul Gawande has put it, when you are sick, “it’s not science you call upon but a doctor.” It is this fundamentally human endeavor of surgery, always rooted in specific social and historical contexts, that is the subject of this course. We kick off the semester with a pilgrimage to the Ether Dome of Massachusetts General Hospital, where the first successful surgery under anesthesia was performed in 1846. By comparing historical and present-day accounts of surgical success and failure, we explore what surgery has demanded from practitioners and patients over time. We next examine one of the fields of surgery that has generated the most controversy and soul-searching throughout its history in societies around the world: organ transplantation. Focusing on the world’s first attempts at the transplantation of still-beating hearts, we ask how medical advances and surgical achievement have challenged our very concepts of life and death. Lastly we consider an array of very different types of surgery that can significantly affect one’s identity, self-presentation, and social position, such as cosmetic, bariatric, gender reassignment, and cochlear implant surgeries. Through independent research projects on related surgical phenomena of their choice, students will explore how the advent and availability of certain types of surgery in particular contexts has shaped social norms, concepts of the normal and the pathological, prevailing principles of medical ethics, and individual experience and self-understanding. What constitutes necessity, medical or otherwise? What should we be empowered to choose—and how far should we be allowed to go? And what are the implications when the way we respond to social problems is with a surgeon’s knife?' 
		elif faculty[0][2] == 'Terrones' :
			title = 'HIV/AIDS in Culture'
			description = 'Perhaps more than any other event in the last quarter of the twentieth century, the AIDS crisis condensed or crystallized cultural anxieties about the body, identity, and difference. From the early reports of a ‘gay cancer’ in the New York Times to contemporary fundraising campaigns like Project RED, public discourse surrounding the virus has often been more concerned with who contracts it and how rather than with its biological causes or medical treatment. In this course, we will examine the cultural response to HIV/AIDS in the Americas through fiction, poetry, and visual art from the pandemic’s first fifteen years. We will begin by looking at the different metaphors and allegories deployed in the early eighties to conceptualize the disease through short fiction from the U.S. and Brazil. How was AIDS figured when it first burst into public consciousness? How did activists, writers, and artists feed into these notions or push against them? In our second unit, we will consider the relationship between the visual arts, poetry and activism in the second half of that decade. How did activist groups such as ACT UP and Yeguas del Apocalipsis mobilize art to try to effect change in public consciousness and policy? How was art across the hemisphere shaped by the intense public debates surrounding it? The course will conclude by focusing on two longer works from the early nineties: Tony Kushner’s Angels in America and Mario Bellatín’s Salón de belleza. How do these two texts construct or demolish overarching narratives about the epidemic? What role does each see for art in combating the disease? Throughout the semester, we will make use of the insights provided by theorists and activists of the period —such as Susan Sontag, Douglas Crimp, Pedro Lemebel and Simon Watney— along with perspectives from a variety of disciplines including political science, epidemiology, and history of science. No knowledge of Spanish or Portuguese is necessary: all materials will be available in English.'
		elif faculty[0][2] == 'Greenup':
			title = 'Humans, Nature, and the Environment'
			description = 'Deforestation, overpopulation, pesticide use, toxic oceans, endangered species, global warming. How are we to make sense of the many environmental problems facing the Earth today? Although the sciences provide a factual account of environmental threats and ways of countering them, scientific facts seem not to be enough, since artists, writers, filmmakers, and even scientists find themselves turning again and again to their imaginations to respond to the environmental predicaments of industrial society. They may be doing what English Romantic poet Percy Shelley powerfully described 200 years ago as an essentially human and creative impulse: “to imagine that which we know.” How, then, have creative minds imagined – in essays, books, and movies – the very idea of nature, the place of humans in it, and their power to change the environment? In this course, we will consider both the possibilities and the problems that writers and filmmakers have imagined about human interactions with the natural world. We begin with the nineteenth century, when Romantic writers were urgently contemplating the meaning of nature in an age of increasing industrialization. In the first unit we interpret “Walking” (1862), the naturalist Henry David Thoreau’s seminal nature essay that imaginatively explores the concept of wildness. In the second unit we will critically compare the literary approaches of two popular books by scientists – Rachel Carson’s Silent Spring (1962), and James Lovelock’s The Revenge of Gaia (2006). And in the final unit we will examine the techniques of documentary movies about relationships between humans and animals – Werner Herzog’s Grizzly Man (2005) in which the filmmaker takes issue with the self-proclaimed environmentalist Timothy Treadwell who strove to protect bears in the Alaskan wilderness, and Gabriela Cowperthwaite’s Blackfish (2013) in which she delivers a brilliant polemic against the Sea World corporation and its treatment of captive killer whales.'
		elif faculty[0][2] == 'Krakauer':
			title = 'Darwinian Dating'
			description = 'Among animals, individuals choose mates based on biologically informative features such as long colorful tail feathers or a red posterior. We typically assume that human attraction (and love) is more nuanced and complex, but is it? Many features that humans find attractive, such as small waists, curvy hips, nurturing behavior, and dominance, can be tied to biological explanations. In this course we will explore biological explanations for these, and many other, aspects of human attraction. Using an evolutionary perspective, we will examine global patterns of attraction and challenge stereotypes of beauty. Are the Barbie-like women of Hollywood really most attractive to men? Do nice guys truly finish last? Do traditionally attractive features in western cultures—such as large breasts—actually provide an evolutionary benefit, or might some be false signals? In addition to exploring the biological roots of attraction, we will examine how principles of attraction are expressed in popular culture, as well as how they play out right here on a college campus. In the first unit, we will attempt to define the ongoing fundamental debate between those who explain human behavior like attraction as the result of evolution and those who see such behavior as determined by culture. We turn next to a comparison of the divergent explanations that have emerged in the body of research on female attraction. How do we reconcile some studies\' findings that women want strong, aggressive men with high testosterone and large incomes with the findings of other studies showing that women prefer nurturing and intelligent men with slightly “feminine” qualities and facial features? Having wrestled with the question of what women want, our course concludes with the analogous question of what men want. Students will have an opportunity to undertake independent research as they explore the nature of male attraction in an era of complex messages about female beauty.'
		elif faculty[0][2] == 'Liazos':
			title = 'Class, Race, and Space in Boston'
			description = 'This course explores the interplay between the physical spaces of American cities and the class and racial identities of urban residents. Focusing on Boston’s and Cambridge’s history from the 1960s to the present, we ask how spaces (from sidewalks to university campuses) shape residents’ images of themselves and their neighbors. Course readings and assignments emphasize the contested nature of decision making processes, focusing on debates among politicians, courts, university officials, and neighborhood groups to determine residential and educational policies. We begin by examining a pioneering work in the field of urban studies: Jane Jacobs’s The Death and Life of Great American Cities (1961). Jacobs vehemently critiqued programs for urban renewal and instead celebrated the vitality of social spaces found in older urban neighborhoods such as Boston’s North End and New York’s Greenwich Village. We then turn to one of the most tumultuous times in Boston’s history as we investigate the protests surrounding the implementation of forced busing to integrate the Boston Public Schools in the 1970s. This period continues to be the subject of considerable debate, with scholars offering conflicting accounts of the role of racial, ethnic, class, and gender-based identities among opponents of busing. We build on the skills developed in the first two assignments in a final research paper that considers Harvard’s own history of class, race, and space. Students first explore scholarship regarding “town gown” relations more generally and then conduct original research regarding a key episode in Harvard’s interactions with neighboring residents in Boston or Cambridge.'
		elif faculty[0][2] == 'Martin':
			title = 'Society and the Witch'
			description = 'Riding broomsticks and dancing in the woods at night, witches are often imagined to be outside society. But in these representations may be keys to understanding social norms, norms that get articulated through the witch’s very violation of them. In this seminar, we ask what discourses about witches tell us about the societies that produce them. We begin by examining anthropologists’ depictions of witchcraft among people who come to find magic believable: how do we understand the seemingly irrational idea that magic is real? Closely considering evidence from classic ethnographic accounts, we critically examine other scholars’ answers to questions such as this one by thinking across competing approaches to the study of magic. Next, we analyze the film Harry Potter and the Chamber of Secrets and the television sitcom Bewitched, bringing these pop-cultural phenomena into conversation with Mary Douglas’s treatise on Purity and Danger and Pierre Bourdieu’s critique of Masculine Domination. These theories help us examine, for example, how fictional representations of witches speak to political struggles over class and gender. For the research paper, each student chooses an example of witchcraft on which to conduct independent research. Sample topics include fairy tales, the Salem witch trials, neo-paganism, and the Broadway musical Wicked. What will unite our diverse inquiries is a common interest in the social significance of this seemingly marginal figure: the witch.'
		elif faculty[0][2] == 'Mounk':
			title = 'Democracy in the Digital Age'
			description = 'Information technology has transformed politics with breathtaking speed. Today, citizens promote their favorite causes on Facebook, politicians announce they are running for office on YouTube, and journalists discuss the latest gaffe on Twitter—all platforms that did not even exist a decade ago. The internet has also affected autocratic regimes. From Egypt to Turkey, activists have used social networks to organize protests. But have these changes been as important, and as positive, as is widely claimed? We start by gaining a better understanding of the nature and history of democracy. Are competitive elections the cornerstone of democratic government, as we tend to assume, or are they actually the hallmark of an aristocratic system, as the Ancients believe? Is it democratically justified for nine Supreme Court justices to decide which laws remain on the books? And did the Founding Fathers actually set out to institute a democratic form of government? Next, we look at technology’s impact on contemporary democracies, both in the United States and around the world. Did social networks lead to the Arab Spring—or could protestors have ousted Mubarak and Gaddafi by relying on leaflets and landlines? And has the internet deepened democracy by making it easier for ordinary citizens to organize—or has the rise of partisan “echo chambers” eroded the quality of public discourse? Finally, we assess whether new technologies call for new political institutions. It used to be impossible for geographically dispersed citizens to deliberate about politics with each other on a regular basis. Today, everyone can come together online to debate pressing issues. So should we adopt more direct forms of democracy? To answer these questions, we consult studies by social scientists, read the Twitter feed of the Syrian opposition, watch a documentary about the protestors in Tahrir Square, analyze the rise of the Tea Party and Occupy Wall Street and study a short story by Isaac Asimov.'
		elif faculty[0][2] == 'Mukherjee':
			title = 'Colonialism and Resistance'
			description = 'In Shakespeare’s seemingly fairy-tale-like play, The Tempest, a god-like European magician tames an ugly monster on an island far removed from Europe. In Heat and Dust, a cross-cultural novel written centuries later by European author, Ruth Prawer Jhabvala, heroic British rulers save powerless widows in India from the monstrosity of being forced to burn themselves on their husbands’ funeral pyres. Yet European power over non-Eurocentric cultures does not go unchallenged: so, we find Shakespeare’s monster begin to plot revenge against the powerful European magician. And even more strikingly, in the hugely popular contemporary British movie, Bend It Like Beckham, a non-western teenaged girl—instead of being saved by English heroes—now starts dreaming of bending the soccer ball herself like the heroic David Beckham! In this course, we’ll explore some of the myriad ways in which creative voices from different times capture the phenomenon of colonialism, the process by which European nations systematically gained power over much of the non-European world, producing effects that reverberate globally to this day. At the same time, we’ll analyze how such narratives depict the equally significant ways in which non-European peoples resisted colonial power and continue to resist its ongoing legacy. We’ll begin by reading The Tempest, a fascinating tale of magicians and monsters, princesses and sprites, shipwrecks and islands that raises profound questions about the forcible manner in which Europeans established colonies in the New World, as well as the violent ways in which natives resisted them. Does this English play represent the forceful strategies of the Europeans and the violence of the natives in a manner that justifies the early colonial project as necessary for improving “lesser” peoples or that critiques it as unjustified in ousting locals? Our second course unit transitions to modern colonialism, the more full-fledged political, economic, and cultural domination of non-European nations. With the help of leading postcolonial theorist Edward Said, we’ll examine Heat and Dust as a window to understanding a complex form that colonial power and acts of resistance to it can take: what happens, in other words, when those in power and those opposing it don’t use sheer force but rather ideas and language as their tools for empowerment? We’ll conclude the course by comparatively considering the movie, Bend It Like Beckham, alongside three short stories by Albert Camus, Salman Rushdie, and Sherman Alexie, respectively, to evaluate avenues as varied as sports, religion, standardized tests, and even recreational drugs through which today’s post-colonial populations across the globe engage in dismantling the colonial legacy. As we do so, we’ll also ask what kinds of role, if any, formerly colonizing European powers should play in such endeavors.'
		elif faculty[0][2] == 'Hayden':
			title = 'The Psychology of Success and Failure'
			description = 'Who gets ahead in America? Why do some succeed while others fail?  How do we account for the influence of various complex factors—societal, community, family, and individual psychology, to name just a few? How do adolescents today handle the pressure to achieve what seems to go hand-in-hand with being an American teenager? In this course, we will examine questions of success, failure, achievement, and identity viewed through the lens of current theories in psychology. We will begin with a longitudinal, ethnographic study of four American children. Through case material that details their daily lives, we will explore how factors like race, gender, and the wealth of their families affected these children’s lived experiences of childhood and, when they were older, their chances of successfully getting into college. Next, we will examine two popular narratives of success and failure—the documentary film Hoop Dreams, which tells the story of two teenagers from Chicago who aimed to be good enough at basketball to play for the NBA, and The Overachievers, a best-selling journalistic account of the pressure for academic achievement felt by students at an elite public high school on the East Coast. We’ll read sources that explore how passion, motivation, and a quest for competence all contribute to an individual’s drive to succeed. In the final unit of the course, we will explore the consequences of achievement pressure on students’ mental health during the college years, examining research on topics such as sleep deprivation, perfectionism, depression, and suicide. Throughout the course, we will use psychological theory to motivate questions and answers about human behavior in a society where the demand for success can be tantalizingly high and the fear of failure devastatingly relentless.'
		elif faculty[0][2] == 'Johnson':
			title = 'Tragedy and Everyday Life'
			description = 'The image of Oedipus blinding himself at the end of Sophocles\' Oedipus Tyrannus is among the most violent in Western drama. Realizing that he has killed his father, married his mother, and brought a plague upon his people, Oedipus represents a human scenario too horrible to imagine. And yet Western culture does imagine it—it can\'t seem to stop imagining it—and the most horrible thing about the tragic fate of Oedipus is the suggestion that tragedy lurks within each of us as a fundamental risk of human existence. In this course we will examine tragedies both ancient and modern, asking why certain human scenarios are supposed to be tragic and whether those scenarios represent states of exception within the ordinary range of human experience—or exceptions that prove an unsettling rule. In Unit 1 we will read Sophocles\' Antigone (442 BCE), examining the structure of tragic conflict and considering the manner in which this particular structure reflects the form of critical debate more generally. In Unit 2, we will compare Sophocles\' Oedipus Tyrannus (429 BCE) and Shakespeare\'s King Lear (1606), asking whether the criteria of self-knowledge that plague Oedipus remain stable after two millennia or present themselves in a new "modern" fashion. In Unit 3 we will view a selection of films, including Vertigo (1958), Persona (1966),  Memento (2000), and Black Swan (2010), asking whether the tragedy of contemporary culture can be understood as an everyday and insoluble conflict between individuals, themselves, and the societies in which they live.'
		elif faculty[0][2] == 'Doherty':
			title = 'War Stories'
			description = 'How should we represent the horrors of war, and how should we remember it? These are questions that have fascinated writers since the time of Homer, but the answers to these questions changed in the modern era, when war started to seem less noble and heroic and more totalizing and destructive. This course looks at artistic representations of modern warfare and asks what effects war has on those who survive it. What happens when the body is whole, but the mind is broken? How does war live on the memories of those who fought, or in the collective memory of a nation? Can—or should—art be made out of these painful, violent experiences? We’ll start off with Tim O’Brien’s The Things they Carried, a powerful collection of stories based on O’Brien’s experiences as a solider in Vietnam. The stories encourage us to ask how truthfully we remember and what moral judgments we make when we choose which stories to tell. From there, we’ll pursue questions about memory and morality further by studying literature about the Great War, including Ernest Hemingway’s A Farewell to Arms. We’ll ask how national politics form in and around these wars and their legacies. Our last unit brings all of these topics together as we move from literature to the movies. We’ll watch Francis Ford Coppola’s Apocalypse Now, a movie that quickly became a classic of New Hollywood, and Zero Dark Thirty, Kathryn Bigelow’s recent depiction of the War on Terror. Throughout the course, we’ll debate whether the experience of war can ever be adequately communicated to those who weren’t there, and whether these attempts can prevent future generations from repeating the mistakes of the past.'
		elif faculty[0][2] == 'Rosenzweig':
			title = 'Jewish Identity in American Culture'
			description = 'What does it mean to be Jewish in America in 2016? At a time when a majority of American Jews do not belong to a synagogue and an estimated one-third of married American Jews are married to non-Jews, is there such a thing as a shared identity among American Jews? This course will examine representations of Jews in American culture in an attempt to understand how Jewish-American culture has evolved since World War II, as well as how shifts in the cultural conversation about minorities in America have affected our conception of Jewish identity. As we consider recent works of literature, art, film, and television, we will question how they challenge and reinforce Jewish stereotypes, and how they continue to shape our ideas about assimilation, the Holocaust, ethnicity, and religious practice in America. We will begin by examining stories of assimilation by authors including Grace Paley, Allegra Goodman, Philip Roth, Nathan Englander, and others. We will then consider representations of the Holocaust, including Art Spiegelman\'s Maus, Judy Chicago\'s Holocaust Project, and Larry David\'s Curb Your Enthusiasm "survivor episode.” In the final unit of the course, students will choose their own sources as they research and develop their ideas about Jewish identity in American culture.'
		elif faculty[0][2] == 'Summerhays':
			title = 'Reading the Body'
			description = 'What does it mean—and what has it meant—to have a body?  Is a body a physical boundary separating a self from the rest of the world?  If so, how do we account for cases like contagion or reproduction, where bodies implicate one another?  How does the way we think about our bodies depend upon both the technologies we use to manage, diagnose, and measure them and the artistic forms we use to represent them?  We’ll begin to explore these questions by visiting the Warren Anatomical Museum and the Putnam Gallery to examine Harvard’s morbidly fascinating collections of medical curiosities and instruments—which include phrenological models of the brain, fetal skeletons, medical diagrams and prints, early X-ray machines, Civil War surgical instruments, and even Phineas Gage’s skull.  In our second unit, we will read across the boundaries of theology, literature, and science—genres we usually imagine as distinct—to understand how writers from a range of perspectives have grasped and represented the origin, construction, and development of the human body.  We will examine the works of Jean Baptiste de Lamarck, William Paley, and Charles Darwin and analyze A. S. Byatt’s treatment of their debate in her novella, “Morpho Eugenia.”  This interest in how the body has been understood in the past will inform your final research paper, where you will analyze representations of the body in the contemporary texts or contexts of your choice.  Possibilities include (but are not limited to) disease films, modern dance, nude portraiture, college athletics, fitness magazines, and advertising.  Throughout the semester, we will ask how and why the body has been theorized in such conflicting ways, calling into question any singular understanding of what constitutes a human body.'
		elif faculty[0][2] == 'Sinnott':
			title = 'Surveillance: Legal and Ethical Issues'
			description = 'When we think of the trade-off between freedom and security, most of us assume that our own freedoms will not be threatened. This assumption has been upended by recent leaks by former NSA contractor Edward Snowden, which have revealed widespread surveillance by the U.S. government. It is easy to denounce the NSA’s programs as Orwellian, or, on the other hand, to reassure ourselves that surveillance only harms those with something to hide. In this course we will seek to move beyond these simplistic responses by closely examining the NSA programs and by considering the underlying rights at stake in surveillance.  In the first unit, we will begin with an exploration of the powerful, but surprisingly elusive, concept of privacy. Are we concerned only that the government might abuse the information it gathers, by blackmailing political enemies, for instance? Or is there something more fundamentally troubling in the government being privy to people’s communications? In the second unit, we will consider the NSA’s collection and review of telephone metadata from within the United States. Is it an unacceptable infringement of privacy for the government to collect information about whom we call and when, as distinct from the content of our calls? We will examine in detail the decisions of two federal judges who reached diametrically opposed answers to this question. In the final unit of the course, we will tackle the NSA’s power to monitor the content of calls and emails originating from non-American citizens who are outside the United States. Do these non-citizens have any privacy rights vis-à-vis the U.S. government? Are there adequate legal protections for American citizens whose communications—both dangerous and innocent—are swept up in surveillance that is targeted at foreigners? For this unit, students will write a research paper about the appropriate limits on the NSA’s powers to eavesdrop on private conversations.'
		elif faculty[0][2] == 'Davies':
			title = 'Representations of American Democracy & Government'
			description = 'Beyond the abstraction of American democracy as government of, by and for the people, what does democracy look like in its physical manifestations? What can we glean about our definitions of and faith in American democratic governance from historical and artistic representations of it? This course will examine what U.S. democracy looks like—its electoral mechanics, its collective bodies, its buildings, and its personality—when brought to life in campaign commercials, architecture, and films. We will ask what these representations of government suggest about the political ideals they ostensibly embody. How do the depictions of government in these works shape our understanding of the possibilities and constraints of democratic action? In what ways can citizens participate (or not) in these figurations of government? Our first unit will explore presidential television advertisements from the 1952 to the recent salvos of the 2008 campaign. With an eye to uncovering how their narratives, imagery, rhetoric, and stagecraft imply particular assumptions about democratic governance, we will examine how such commercials ask us to consent to a particular version of “government by the people.” In our second unit we will study the architecture of the Massachusetts State House (which we will examine in person) and a few of Washington, D.C.’s federal buildings—the Capitol, the White House, the Supreme Court Building, and the Pentagon. Analyzing architectural drawings, photos, paintings, and online tours of these buildings, we hope to uncover not just the symbolism of their styles but the effect that their shape and allocation of space have on individual and collective behavior. We will compare, in our final unit, conceptions of government in several conspiracy-theory films: The Manchurian Candidate, All the President’s Men, JFK, Wag the Dog, and State of Play. We will consider how each film reflects fears commonly held at the time of its creation—fears of communist infiltrations, presidential abuses of power, or corporate manipulations of government officials, among others. How do the respective fears depicted in these films challenge our definitions of democracy? How do such narratives reinforce our relationship with government?'
		elif faculty[0][2] == 'Fee':
			title = 'Social Worlds of Friendship'
			description = 'Most of us are convinced about the importance of friendship, but do we really understand how friendships are formed and how they shape our lives? And might friendship have a larger potential, beyond everyday personal connections? In Unit 1 we will explore Emerson’s essay “Friendship” (1841) to better understand the complex relationship between friendship and the modern, mutable self. Pointing to the many contradictions of friendship, Emerson will even ask us to consider if our closest friends actually make us revel in our solitude. In the second unit, we will emphasize community-building and “social capital,” which can be understood as the many benefits that come with having numerous friendly sets of relationships. Here, we will ask whether or not we live in a society that – in its organization and in its ethos – really promotes these friendly relationships. More specifically, Unit 2 will address the state of our personal communities at a time when so many of us increasingly rely on distant, mediated, or Facebook-type “friends.” Finally, the third component of the course will explore how friendships can potentially be a transformative force in society, especially when they are formed across boundaries of difference. We will venture into how friendship can potentially incite us to challenge interpersonal and social boundaries, thus inspiring us to enlarge our sense of social justice and affinity to others.'
		elif faculty[0][2] == 'Mumme':
			title = 'The Ethics of Human Experimentation'
			description = 'In order to learn about human biology and behavior, researchers often have to study people directly by having them participate in their studies as research subjects. On the one hand, scientific research on humans has produced many social benefits – finding cures for life-threatening illnesses, improving human decision-making, identifying effective treatments for mental illness. On the other hand, there is the risk that the experimental procedures leading to these discoveries might somehow harm the study participants. In this course, we will learn about psychological and biomedical studies that have pushed ethical boundaries, consider their costs and benefits, and analyze why they were done in the first place and whether they could be done differently to minimize the risks to the human participants. We will begin with an analysis of Milgram’s classic social psychological study of obedience and consider its ethical challenges and its contributions to the study of human behavior. We will next turn to a historical account of a study that was clearly unethical (The Tuskegee Syphilis Study) and apply a social psychological analysis as a way of understanding why this study took place and why it persisted for so many years. In the final unit of the course, you will have an opportunity to explore and evaluate research at Harvard by participating in or investigating psychology studies currently taking place on campus.'
		elif faculty[0][2] == 'Greenspan':
			title = 'Cities and Globalization'
			description = 'Globalization is one of the most defining, and fraught, phenomena of modern times. Social media and international travel connect people and places at unprecedented speeds; growing gaps between rich and poor disconnect individuals within and across nations. In this course, we’ll investigate how ‘the global city’ brings to the fore the opportunities and challenges of contemporary globalization. How and why do specific economic and cultural forms link cities like New York, Los Angeles, Paris, and Mumbai? How is urban protest and unrest a response to globalization? What problems, questions, and arguments cut across fictional and non-fictional representations of cities in various parts of the world? We will answer these questions by reading a variety of texts on cities - including theoretical works by Saskia Sassen and Ulf Hannerz; and literary non-fiction like Suketu Mehta’s Maximum City - and viewing artistic interpretations like Mathieu Kassovitz’s film ‘La Haine.’ We will begin the course by reading classic texts to understand how global cities have emerged and why they share unique features – including diverse populations, iconic architecture, and finance-based economies. Then, we will examine how these broad, macro trends have played out in particular cities, including Paris and Mumbai, and how they have been depicted by writers and artists. Lastly, we will examine how groups have protested – sometimes violently – against aspects of life in global cities and aspects of globalization more broadly. Students will conduct independent research on an instance of urban protest/violence to develop their own arguments about the contradictions of globalization in different parts of the world.'
		elif faculty[0][2] == 'Brown':
			title = 'Imagining the Wild West'
			description = 'From a whistle-stop town with a gun-slinging sheriff to a desperate landscape filled with danger, where the American Dream appeared to come true, the West has occupied a central place in the American imagination for three centuries. But the West is a place whose imagined reality has often been at odds with its written history—a place where an ideal of rugged individualism coexists with massive federal management, where white men have been remembered and diverse populations forgotten, and where new opportunities have collided with bloody conflict. In this course, we will examine how Americans have remembered the West—how they have decided which stories to tell and which to bury. To answer these questions, we will examine the peculiar histories of Western myths, focusing on the invention and reinvention of the Wild West in American pop culture. For our first unit, we will develop our close reading skills as we investigate memoirs detailing the “real” lives of Westerners—a Dakota woman stripped of her identity, a homesteader on the brink of starvation, cowboys both white and black, and immigrants dying for their rights. In unit two, we will turn to Buffalo Bill, the quintessential Wild West hero who brought in crowds of thousands across the country and reenacted Custer’s Last Stand for the Queen of England. Students will consider Buffalo Bill in the context of Victorian ideas about men, women, and race as we attempt to explain why this story, which was essentially a Victorian fantasy, so powerfully captured the American imagination. What does Buffalo Bill’s fame tell us about who Americans thought they were, or thought they could be? Finally, in unit three, we will examine how the myths of the Wild West have survived into modern pop culture through movies, television, and fashion. Whether it’s George W. Bush posing as a cowboy president or bearded hipsters working at MacBooks while dressed as lumberjacks, these myths continue to animate our culture. For their final paper, students will choose a representation of the West in popular culture to research with the goal of understanding why these myths remain powerful and what assumptions underpin them. What does Toy Story have to do with Victorian office workers, or modern libertarians with last century’s paperbacks? Is HBOS’s Deadwood a show about the 1880s, or a comment on modern capitalism? What do the Coen Brothers have in common with John Wayne?  And when we tell stories about the Wild West, when we choose what to forget and what to immortalize, what are we saying about ourselves?'
		elif faculty[0][2] == 'Bellanca':
			title = 'Gothic Fiction'
			description = 'Horror, madness, monstrosity, death, disease, terror, evil, and weird sexuality: these preoccupations, according to a recent critic, have animated Gothic fiction ever since it emerged in the mid-1700s. We will contemplate these preoccupations as we examine a range of Gothic texts from eighteenth-century Gothic fragments to stories by Edgar Allan Poe and Isabel Allende. And we will ask these questions about those texts: What makes Gothic fiction “Gothic”? How do we account for its immense popularity? Why have high-minded readers and writers always tended to scorn it? (What are they so worried about?) And what have modern Gothic writers and readers made of the genre they’ve inherited? We’ll develop a working definition of the Gothic in our first segment, which will take a group of short stories—of various centuries and nations—as its primary texts. Next, we’ll read Jane Austen’s Gothic spoof, Northanger Abbey, in the context of both the popular fiction Austen parodies and the heated eighteenth-century debates about what young women should read. Our third segment will focus on Edgar Allan Poe and his tales of paranoia, insanity, and incest. This segment will extend the course’s focus from the Gothic mansion (and the Gothic monster) to the Gothic mind.'
		else:
			pass
			# print course

	courseDict['shortField'] = shortField
	courseDict['number'] = number
	courseDict['title'] = title
	displayTitle = shortField + ' ' + number + ' ' + title
	if displayTitle in allCourses:
		merged = mergeCourseDicts(allCourses[displayTitle], courseDict)
	else:
		allCourses[displayTitle] = courseDict

	titles[displayTitle] += 1

	continue
# for title in titles:
# 	if titles[title] == 2:
# 		print titles[title], term, year, title 
	# if value > 1:
	# 	print key

with open('parsedCourses.json', 'w') as fp:
    json.dump(allCourses, fp)
# print allCourses['COMPSCI 181 Machine Learning']
# print '----------------- ' + str(len(commas)) 
# print '\n'.join(commas)
# print '----------------- ' + str(len(ands)) 
# print '\n'.join(ands)
# print '----------------- ' + str(len(oneName)) 
# print '\n'.join(oneName)
# print '----------------- ' + str(len(oddballs)) 
# print '\n'.join(oddballs)